#!/usr/bin/env python

"""
Create or update a TOML file of tweet IDs for add_tweets to use.

Usage: add_timeline <screen_name>
"""

import os
import sys

import toml

from lib.twitter import Twitter


twitter = Twitter()
account = sys.argv[1]

data_file = 'data/%s.toml' % account
page = 0
ids = []

# first, read in the file if it exists
try:
    with open(data_file, 'r') as handle:
        tweets = toml.load(handle)
except FileNotFoundError:
    tweets = {}

# fetch tweets
while True:
    page += 1
    timeline = twitter.user_timeline(
        account,
        page = page,
        tweet_mode = 'extended'
    )
    if len(timeline) == 0:
        break
    for tweet in timeline:
        ids.append(tweet.id_str)

# twitter is most-recent-first, I like least-recent-first in my config file
for id in reversed(ids):
    if id not in tweets:
        tweets[id] = {}
        twitter.create_source_from_tweet(id, tweets[id])

with open(data_file, 'w') as handle:
    toml.dump(tweets, handle)
