#!/usr/bin/env python

"""
Create a TOML file of tweet IDs for add_tweets to use.

Usage: add_timeline <screen_name>
"""

import os
import sys

import toml
import tweepy


auth = tweepy.OAuthHandler(
    os.environ['CONSUMER_KEY'],
    os.environ['CONSUMER_SECRET'],
)
auth.set_access_token(
    os.environ['ACCESS_TOKEN'],
    os.environ['ACCESS_TOKEN_SECRET'],
)
twitter = tweepy.API(auth)
account = sys.argv[1]

page = 0
ids = []
data = {}
while True:
    page += 1
    tweets = twitter.user_timeline(
        account,
        page = page,
        tweet_mode = 'extended'
    )
    if len(tweets) == 0:
        break
    for tweet in tweets:
        ids.append(tweet.id_str)

# twitter is most-recent-first, I like least-recent-first in my config file
for id in reversed(ids):
    data[id] = {}

filename = 'data/%s.toml' % account
with open(filename, 'w') as handle:
    toml.dump(data, handle)
