#!/usr/bin/env python

import csv
from datetime import datetime, timezone
from io import StringIO
import os
import re
import requests

from lib import update_content


req = requests.get('https://gifs.cackhanded.net/index.csv')
req.encoding = 'utf-8'

gifs_input = StringIO(req.text)
reader = csv.DictReader(gifs_input)
gifs_output = StringIO()

fields = [
    'slug',
    'published',
    'title',
    'original_title',
    'url',
    'gif',
    'thumbnail',
    'tag[]',
    'origin',
    'origin_link_url',
    'type',
]
writer = csv.DictWriter(gifs_output, fieldnames=fields)
writer.writeheader()

for row in reader:
    timestamp = datetime.strptime(
            row['published'],
            "%Y-%m-%dT%H:%M:%SZ"
        ).replace(tzinfo=timezone.utc)
    row['slug'] = '/%s/%s' % (
        timestamp.strftime('%Y/%m/%d'),
        os.path.basename(row['url'])
    )
    row['origin'] = 'gifs'
    row['origin_link_url'] = row['url']
    row['original_title'] = row['title']
    row['title'] = 'Published GIF “%s”' % row['title']

    # use the source/episode parts of the URL as tags too
    parts = row['url'].split('/')
    if len(parts) == 6:
        sources = parts[3:5]
    elif len(parts) == 5:
        sources = [parts[3]]

    row['tag[]'] = ':'.join([row.pop('tag'), *sources])
    row['type'] = 'gif'
    writer.writerow(row)

update_content('source/gifs.csv', gifs_output.getvalue())
