#!/usr/bin/env python

import csv
from datetime import datetime, timezone
from io import StringIO
import os
import re
import requests

from lib import update_content


req = requests.get('https://gifs.cackhanded.net/index.csv')
req.encoding = 'utf-8'

gifs_input = StringIO(req.text)
reader = csv.DictReader(gifs_input)
gifs_output = StringIO()

fields = [
    'slug',
    'published',
    'title',
    'url',
    'gif',
    'thumbnail',
    'tag[]',
    'source',
    'source_url',
    'type',
]
writer = csv.DictWriter(gifs_output, fieldnames=fields)
writer.writeheader()

for row in reader:
    timestamp = datetime.strptime(
            row['published'],
            "%Y-%m-%dT%H:%M:%SZ"
        ).replace(tzinfo=timezone.utc)
    row['slug'] = '/%s/%s' % (
        timestamp.strftime('%Y/%m/%d'),
        os.path.basename(row['url'])
    )
    row['source'] = 'gifs.cackhanded.net'
    row['source_url'] = row['url']
    row['tag[]'] = row.pop('tag')
    row['type'] = 'gif'
    writer.writerow(row)

update_content('source/gifs.csv', gifs_output.getvalue())
