#!/usr/bin/env python

"""
Add selected tweets from a list of tweet IDs.
"""

import sys

import toml

from lib import update_content
from lib.twitter import Twitter


def main():
    twitter = Twitter()

    account = sys.argv[1]
    ids_toml = 'data/%s.toml' % account

    with open(ids_toml, 'r') as handle:
        ids = toml.load(handle)

    for id in ids:
        if 'ignore' in ids[id]:
            continue
        data = twitter.create_source_from_tweet(id, ids[id])
        ids[id]['title'] = data['title']

    update_content(ids_toml, toml.dumps(ids))

if __name__ == '__main__':
    main()
