#!/usr/bin/env -S bash -euo pipefail

DIFF_BASE='https://github.com/norm/marknormanfrancis.com/commit'

message="${1:-Automated changes}"

git config user.name "GitHub Actions"
git config user.email "actions@users.noreply.github.com"

# if there are any changes/new files ...
if [ -n "$(git status --porcelain)" ]; then
    # ... commit them
    git add -A
    git commit --message "$message"
    git push

    rev=$(git rev-parse HEAD)

    # ... and send an update
    (
        echo "# Updated files"
        echo ''
        echo "[See diff on GitHub]($DIFF_BASE/$rev)"
        echo ''
        git show --pretty='' --name-only $rev | sed -e 's/^/* /'
    ) \
        | ./script/twist_post $(date +'%Y-%m-%d') $message

fi
