#!/usr/bin/env python

from flourish import Flourish
from flourish.source import SourceFile
import os
import sys


flourish = Flourish(
    fragments_dir='fragments',
)

generate = set()
for arg in sys.argv[1:]:
    if not arg.startswith('source/'):
        continue

    file = arg[7:]
    slug, _ = os.path.splitext(file)

    try:
        page = flourish.get(slug)
    except SourceFile.DoesNotExist:
        continue

    generate.add('/%s' % page.slug)
    generate.add('/%d/' % page.published.year)
    generate.add('/%d/%02d/' % (page.published.year, page.published.month))
    generate.add('/%d/%02d/%02d/' % (page.published.year, page.published.month, page.published.day))

    if 'tag' in page:
        generate.add('/tags/')
        for tag in page.tag:
            generate.add('/tags/%s/' % tag)
    if 'thread' in page:
        generate.add('/threads/%s' % page.thread)
    if 'subject' in page:
        generate.add('/%s/' % page.subject)
        if 'topic' in page:
            generate.add('/%s/%s/' % (page.subject, page.topic))

if len(generate):
    generate.add('/index.atom')
    generate.add('/firehose.atom')
    generate.add('/')
    for path in sorted(generate):
        flourish.generate_path(path, report=True)
