#!/usr/bin/env -S bash -euo pipefail

# Mark Norman Francis channel
./script/add_youtube_uploads UUhCfyxtJP1e4eO0v7L1CUJw

# Game Show channel
./script/add_youtube_uploads UUI0KNfM-b2vXKPY4QwJ0_oQ

# import all published content from gifs.cackhanded.net
./script/add_gifs

./script/add_github_events

# import autopublished tweets
./script/publish_tweets

# import @mnfpublishing favourites
./script/mnfpublishing
