#!/usr/bin/env -S bash -euo pipefail

function error {
    echo "$@" >&2
    let "errors = errors + 1"
}


errors=0
files=0

# check filenames for "undefined" posts
while IFS= read file; do
    [[ "$file" =~ /undefined* ]] && error "Undefined: $file"
    [[ "$file" =~ /tweet-* ]]    && error "Untitled tweet: $file"

    let "files = files + 1"
done < <(find output -type f)

# check for broken month navigation
while IFS= read file; do
    error "Broken month nav:" $file
done < <(rg -l 'href=./...././' output || true)

# check for untitled pages
while IFS= read file; do
    error "Page title missing" $file
done < <(rg -l 'SET PAGE TITLE' output || true)

# check for the presence of indexes
while IFS= read dir; do
    [ "$dir" = 'output/css' ] && continue
    [ ! -f "$dir/index.html" ] && error "Missing index: $dir/index.html"
done < <(find output -type d)

# check for default indexes
while IFS= read file; do
    error "Default index page" $file
done < <(rg -l 'INDEX PAGE' output || true)

# summary and exit status code
echo ''
echo "$files files, $errors errors"
[ $errors == 0 ]
